/*
 * Copyright (c) 4.17.15 -- Eduard Prokhor, Huy Ngo, Andrew Leach, Brent Young
 */

package db;

/**
 * Created by andrew on 4/6/15.
 * Instance of a new user that is being accessed from the database or
 * sent to the database.
 */
public class User {

    public static final String USER_PREFS = "userPrefs";
    public static final String PERM_PREFS = "permPrefs";
    public static final String USER_RESET = "passwordReset";
    public static final String USER_ID = "userID";
    public static final String USER_PASSWORD = "password";
    public static final String USER_QUESTION = "secQuestion";
    public static final String USER_ANSWER = "secAnswer";
    public static final String USER_EMAIL = "userEmail";
    public static final String USER_NAME = "userName";
    public static final String USER_AGREEMENT = "agreement";
    public static final String START_TIME = "startTime";
    public static final String END_TIME = "endTime";
    public static final String ALL_USERS = "All_Users";


    /**
     * Private field to hold an instance of the User ID generated by a SQL query.
     */
    private String myUserID;

    /**
     * The following fields are explicity entered and edited by the User.
     */
    private String myUserEmail;

    private String myUserName;

    private String myPassword;

    private String mySecurityQuestion;

    private String mySecurityAnswer;

    private int myResetStatus;


    public User() {

        this.myUserID = null;
        this.myUserEmail = null;
        this.myUserName = null;
        this.myPassword = null;
        this.mySecurityQuestion = null;
        this.mySecurityAnswer = null;
        myResetStatus = 0;
    }

    public String toString() {
        return " Username:" + myUserName + " Email:" + myUserEmail + " ID:" + myUserID + " Password:" + myPassword + " Question:" + mySecurityQuestion;
    }

    public String getUserID() {
        return myUserID;
    }

    public String getEmail() {
        return myUserEmail;
    }

    public void setEmail(final String theEmail) {
        this.myUserEmail = theEmail;
    }

    public String getUserName() {
        return myUserName;
    }

    public void setUserName(final String theUserName) {
        this.myUserName = theUserName;
    }

    public String getPassword() {
        return myPassword;
    }

    public void setPassword(final String thePassword) {
        this.myPassword = thePassword;
    }

    public String getSecurityQuestion() {
        return mySecurityQuestion;
    }

    public void setSecurityQuestion(final String theSecurityQuestion) {
        this.mySecurityQuestion = theSecurityQuestion;
    }

    public String getSecurityAnswer() {
        return mySecurityAnswer;
    }

    public void setSecurityAnswer(final String theSecurityAnswer) {
        this.mySecurityAnswer = theSecurityAnswer;
    }

    public int getResetStatus() {
        return myResetStatus;
    }

    public void setResetStatus(final int theResetStatus) {
        this.myResetStatus = theResetStatus;
    }

    public void setID(final String theUserID) {
        this.myUserID = theUserID;
    }

}