package uw.buuteeq_ponyhax.app;

import java.sql.Date;

/**
 * Created by andrew on 4/6/15.
 * Instance of a new user that is being accessed from the database or
 * sent to the database.
 */
public class User {

    /**
     * Private field to properly encapsulate the Date the User created their profile.
     */
    private Date myDate;

    /**
     * Private field to hold an instance of the User ID generated by a SQL query.
     */
    private long myUserID;

    /**
     * The following fields are explicity entered and edited by the User.
     */
    private String myUserEmail;

    private String myUserName;

    private String myPassword;

    private String mySecurityQuestion;

    private String mySecurityAnswer;


    public User() {

        this.myUserID = 0;
        this.myUserEmail = null;
        this.myUserName = null;
        this.myPassword = null;
        this.mySecurityQuestion = null;
        this.mySecurityAnswer = null;
    }

    public String toString() {
        return " Username:" + myUserName + " Email:" + myUserEmail + " ID:" + myUserID + " Password:" + myPassword + " Question:" + mySecurityQuestion;
    }

    public long getUserID() {
        return myUserID;
    }

    public String getEmail() {
        return myUserEmail;
    }

    public String getUserName() {
        return myUserName;
    }

    public String getPassword() {
        return myPassword;
    }

    public String getSecurityQuestion() {
        return mySecurityQuestion;
    }

    public String getSecurityAnswer() {
        return mySecurityAnswer;
    }

    public void setID(final long theUserID) {
        this.myUserID = theUserID;
    }

    public void setEmail(final String theEmail) {
        this.myUserEmail = theEmail;
    }

    public void setUserName(final String theUserName) {
        this.myUserName = theUserName;
    }

    public void setPassword(final String thePassword) {
        this.myPassword = thePassword;
    }

    public void setSecurityQuestion(final String theSecurityQuestion) {
        this.mySecurityQuestion = theSecurityQuestion;
    }

    public void setSecurityAnswer(final String theSecurityAnswer) {
        this.mySecurityAnswer = theSecurityAnswer;
    }

}