package uw.buuteeq_ponyhax.app;

import android.widget.EditText;

import java.sql.Date;

/**
 * Created by andrew on 4/6/15.
 * Instance of a new user that is being accessed from the database or
 * sent to the database.
 */
public class User {

    /** Private field to properly encapsulate the Date the User created their profile.*/
    private Date myDate;

    /** Private field to hold an instance of the User ID generated by a SQL query.*/
    private long myUserID;

    /** The following fields are explicity entered and edited by the User.*/
    private String myUserEmail;

    private String myUserName;

    private String myPassword;

    private String mySecurityQuestion;

    private String mySecurityAnswer;

    public User(final Date theDate, final String theUserEmail, final String theUserName,
                final String thePassword, final String theSecurityQuestion, final String theSecurityAnswer) {
        myUserID = 0;
        myUserEmail = theUserEmail;
        myUserName = theUserName;
        myPassword = thePassword;
        mySecurityQuestion = theSecurityQuestion;
        mySecurityAnswer = theSecurityAnswer;

    }

    public User() {
        //Default no arg constructor for pulling all data from database
    }

    public long getUserID() {
        return myUserID;
    }

    public String getEmail() {
        return myUserEmail;
    }

    public String getUserName() {
        return myUserName;
    }

    public String getPassword() {
        return myPassword;
    }

    public String getSecurityQuestion() {
        return mySecurityQuestion;
    }

    public String getSecurityAnswer() {
        return mySecurityAnswer;
    }

    public void setID(final long theUserID) {
        myUserID = theUserID;
    }

    public void setEmail(final String theEmail) {
        myUserEmail = theEmail;
    }

    public void setUserName(final String theUserName) {
        myUserName = theUserName;
    }

    public void setPassword(final String thePassword) {
        myPassword = thePassword;
    }

    public void setSecurityQuestion(final String theSecurityQuestion) {
        mySecurityQuestion = theSecurityQuestion;
    }

    public void setSecurityAnswer(final String theSecurityAnswer) {
        mySecurityAnswer = theSecurityAnswer;
    }

}